#!/bin/bash

swaymsg -t get_outputs | grep focused > /tmp/outputs_inf

bg_now_o1=$(cat /tmp/bg_now_o1)
bg_now_o2=$(cat /tmp/bg_now_o2)
bg_now_o3=$(cat /tmp/bg_now_o3)

f_o1=$(sed -n '1p' /tmp/outputs_inf | cut -c 16-19)
f_o3=$(sed -n '2p' /tmp/outputs_inf | cut -c 16-19)
f_o2=$(sed -n '3p' /tmp/outputs_inf | cut -c 16-19)

if [[ $f_o1 == 'true' ]]
then
  wal  -e -t -n -q -i $bg_now_o1 
else
  if [[ $f_o2 == 'true' ]] 
  then
    wal -e -t -n -q -i $bg_now_o2
  else
    wal -e -t -n -q -i $bg_now_o3
  fi
fi

